# Generated by Django 4.2.5 on 2023-10-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_comments_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='startPrice',
            new_name='sprice',
        ),
    ]
