# Generated by Django 4.2.5 on 2023-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctions_auctiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='picture',
            field=models.CharField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
