# Generated by Django 4.2.5 on 2023-10-14 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctions_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='userName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Avis', to=settings.AUTH_USER_MODEL),
        ),
    ]
