# Generated by Django 4.2.5 on 2023-10-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='auctionId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='actionId',
            new_name='auctionId',
        ),
    ]
