# Generated by Django 4.2.5 on 2023-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='categories',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
